### ISSUE TITLE
revisionDesc / flags in framework

### ISSUE THREAD

**Issue by JenniferBunselmeier** [chigc/software#2]
@krottmas 

Wie besprochen habe ich dir eine Statusverfolgungsoption im Framework vorbereitet. 

## Anmerkungen
- Du hast im Erstellungsdatum im `@when` noch die Uhrzeit drin, ist die wichtig? Sonst lass sie lieber raus, das macht die Verarbeitung einfacher (meine Meinung).
- Ich habe die zweite Flag aus dem template gelöscht (Erklärung siehe Bild).
- Ich habe provisorisch mal eine nächste Flag "readyForPublication" eingerichtet als Platzhalter, damit du siehst, wie du weitermachen kannst. Die kannst du natürlich wieder löschen bzw. umbenennen.
- Die Feinheiten der Flags müsst ihr projektintern festlegen. (Ich verstehe die aktuellen Flagtexte nicht ganz.) Ich finde es immer sinnvoll, "fertig"-Flags nach konkreten Schritten zu setzen, also z.B.: 
  - Datei ist aus Liste transformiert / erstellt
  - Metadaten/MsDesc ist vollständig eingegeben
  - Metadaten/MsDesc ist vom Editor kontrolliert
  - Ms ist freigegeben zur automatischen Anreicherung
  - Ms ist freigegeben zur Veröffentlichung 
  - etc.
- Wenn ihr die Verantwortlichen nicht im Freitext eingeben wollt, müsstest du das Modell noch erweitern um `@resp` bzw. `<resp>` 

## Erklärung Funktionalität

![fw](https://github.com/chigc/software/assets/57716517/3df271e6-8f94-417c-bdc7-87a66b3f63c2)

## Erklärung Frameworkeinstellungen

![fwerklaerung](https://github.com/chigc/software/assets/57716517/be0e1537-d36d-41cc-b2ef-793a79149bac)

**Comment by krottmas** [comment]
@JenniferBunselmeier Danke fürs vorbereiten :) hab das schon miteingearbeitet :)
