### ISSUE TITLE
@ana / attributes for RDF mapping

### ISSUE THREAD

**Issue by jakobsonnberger** [chigc/software#3]
@krottmas 
Ein paar Attribute haben sich lt. Datenmodell noch geändert:

- [x] für `//msDesc/t:msContents/t:msItem/[t:locus|t:incipit|t:explicit]` will Roman noch jeweils ein `@ana="chigc:locus|chigc:incipit|chigc:explicit"`
- [x] aus `//t:msDesc/t:history/t:origin/t:date/@ana="crm:E52_Time-Span"` soll (vorerst) `@ana="chigc:date"` werden
- [x] typo (hasWidth) in `//msDesc/t:physDesc/t:objectDesc/t:supportDesc/t:extent/t:width/@ana="memo:hasWitdh"` 
- [x] aus `//t:titleStmt/t:title/@ana="dcterms:title"` soll `@ana="rdfs:label"` werden

**Comment by krottmas** [comment]
to do in Framework:

- [x] für `//msDesc/t:msContents/t:msItem/[t:locus|t:incipit|t:explicit]` will Roman noch jeweils ein `@ana="chigc:locus|chigc:incipit|chigc:explicit"`
- [x] aus `//t:msDesc/t:history/t:origin/t:date/@ana="crm:E52_Time-Span"` soll (vorerst) `@ana="chigc:date"` werden
- [x] typo (hasWidth) in `//msDesc/t:physDesc/t:objectDesc/t:supportDesc/t:extent/t:width/@ana="memo:hasWitdh"` 
- [x] aus `//t:titleStmt/t:title/@ana="dcterms:title"` soll `@ana="rdfs:label"` werden
